### ISSUE TITLE
Can't input/modify Events

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#10]
There is a Date/Time error causing the new Events to not be created and causing existing Events to not be able to be changed. It is likely due to a formatting error. 

To reproduce, open the Events section of Keystone. Create a new Event and after inputting the required responses, click Save. You will receive a Date/Time error. This is also true for changes to a existing Events, so the Date/Time issue will need to be fixed in both places.

**Comment by fedorareis** [comment]
I believe this is fully resolved now. @kyle-fletcher can you test it out and reply to let us know if it is working consistently?
