### ISSUE TITLE
Firebase Notifications

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#12]
Need to switch the apps and Keystone over to using Firebase instead of GCM. 

Keystone needs to be updated with new fields to identify the type of phone being used and allowing for the creation of users from the apps.

Android & iOS apps needs to be updated to allow a login creation on the RideSharing portion of the app. The same login system for leaders can be used, but will need to allow for account creation from the app on the RideSharing screen.

**Comment by fedorareis** [comment]
This will effect CruCentralCoast/CruiOS#57

**Comment by fedorareis** [comment]
I think this is done. Pending testing once the apps have switched over.
