### ISSUE TITLE
Resource Pages - Only 1

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#14]
Resource Pages is only allowing the creation of a single Resource. The Resource Page allows the administrative person (likely a Cru staff member or student without programming experience) to create a web page that the apps will reference for the Resources section. Keystone actually creates the web address for it. The Resource Page section of Keystone should allow for the creation of dozens of resources.

Fix: More than one Resource Page allowed to be created.
Fix: Resources that are specific for a Ministry.
Fix: It is not pulling in the standard Cru fonts when creating the web page. The standard Cru font is not on the list of available fonts, but should be used for all our pages.

**Comment by fedorareis** [comment]
The issue has been resolved and pushed to master. It required deleting the model in the database. I suspect the model in the database was created before the keystone model was finalized so it was causing some issues.
