### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#25]
Keystone currently gives errors to the users that are completely unintelligible. It would be nice if the errors given to users were understandable, giving info to the user about formatting changes needed or something they could easily pass on to the programming team. 

Example is in the Users section, when a phone number is entered incorrectly, an unintelligible error is given. This could be a simple fix with proper error handling to notify the user that the phone number is in the wrong format. Many of these issues happen when data has been entered before enforcement of a particular format was put in place.

**Comment by fedorareis** [comment]
This might need to be done after the migration to Keystone 4.
