### ISSUE TITLE
Bring in Changes from Android App Keystone

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#26]
The Android app team needs to have their changes to Keystone brought in to allow the new features of the Android app to work correctly. These can be found at https://github.com/tylerbwong/slocru-keystone.

**Comment by fedorareis** [comment]
Merged into dev, holding on merge to Master pending testing.

**Comment by fedorareis** [comment]
I'm going to close this since everything appears to work and we are just waiting for some app side changes before it gets merged into master.
