### ISSUE TITLE
User ID's for Searchability on Keystone Admin

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#29]
On some portions of Keystone, when trying to assign a user's name to a role, the user's name is not searchable. The only way to find that user is through their unique database identifying number. For continued user-friendliness, the Keystone admin should allow users to be assigned using their name. This is not a significant issue in testing, but will be an immediate issue when live users are in the system and we have to rely on a programmer to assign the users' roles.

Note: this does not happen with every user in the database; only some are not searchable by their name.

Example: in the Community Group section, many user names are not searchable when trying to assign them as Community Group Leaders.

**Comment by fedorareis** [comment]
Apparently, this is an issue with Keystone 0.3.22. We have moved back to Keystone 0.3.21 for the time being where this issue is not present. In the future, we will be moving to Keystone 4 where this issue also is not present.
