### ISSUE TITLE
Ridesharing - Deleting a ride makes server crash

### ISSUE THREAD

**Issue by esolum** [CruCentralCoast/Keystone#32]
Attempting to delete a ride makes server crash. Even just submitting a delete request through Hurl.it for a ride causes the website to show the "Application Error" screen.

**Comment by esolum** [comment]
Also can't seem to delete rides via the website either. Does not crash however.

**Comment by fedorareis** [comment]
I think I just fixed this. It was failing when trying to send the notification to the people in the ride. It should work now.

**Comment by fedorareis** [comment]
@esolum Ride cancellations work properly now.
