### ISSUE TITLE
Community Group Member Details

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#34]
When a leader looks at their Community Group, they should be able to see their members and get their phone number / email again. This should provide a full roster of their Community Group. The endpoints need to be created for this and the database set to handle this new connection.

**Comment by fedorareis** [comment]
@kyle-fletcher is there a related issue on the iOS repo for adding Users to Community Group Roster when they sign up?

**Comment by fedorareis** [comment]
As of 088cbeeb30a54cff7948b42d792390759fc91163 the underlying model components are in place. The User model now has a Community Groups field for storing what CGs the user is involved in. The Community Group model now has a relationship to the Community Groups field in the user model to show in the admin panel what users are members of the CG. The CG endpoint however currently can not fetch the member data. This will be solved in a future commit.
