### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#35]
We should have different levels of users on the database so that the different user types have access to different things. Different levels that I can think of are admins, programmers, keystone updaters that will be populating it with data, and any standard user that we want to have.

**Comment by fedorareis** [comment]
@kyle-fletcher do we want the Staff, Community Group Leader, Ministry Team Leader, and Summer Mission Leader roles to map to some set of permissions or do we want the roles to be completely separate from the permissions settings?

**Comment by kyle-fletcher** [comment]
It seems like we should initiate custom roles if possible. So if the user is a Ministry Team Leader, they can access just the Ministry Team section. Or if they are a Community Group Leader, then the Community Group section. In both of those cases, they should not have the ability to delete.

In addition, we would need admin users that can do anything and a role for the keystone updaters who will be doing events, ministry teams, and community groups.
