### ISSUE TITLE
User: Change Password

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#36]
From the Keystone website, it would be great if a user who does not have permission to "administer the website" was allowed to change their password upon logging in. These users currently have the ability to login, it just tells them that they are signed in and doesn't take them anywhere. Since we created all the passwords for leaders, it would be super helpful to allow them to change their passwords to something that they would prefer. 

It would also be helpful to dictate the type of password being created. It should be a combination of uppercase and lowercase letters as well as numbers of at least 8 characters long. 

Preference would be to have this up for 1.2 Release.

**Comment by fedorareis** [comment]
@kyle-fletcher I’m not sure the server has an endpoint for this at the moment.

Also I’m going to disagree on the password constraints based off a lot of research done within the last few years while yes short passwords should be a combination of letters numbers and symbols in a random order. It is far better to have a long memorable passphrase that might only contain lowercase letters. This is explained well at https://www.xkcd.com/936/ and even the national security standards are moving towards simple pass phrases over complex passwords. We could do a tiered system like Cal Poly does where a certain level of complexity is required below a certain character count. But I much more prefer a simple system that requires the user to have at least 8 characters and will accept anything (letters, numbers, and all symbols) that meet that character count.

**Comment by kyle-fletcher** [comment]
As long as the password is at least 8 characters, I'm fine with it!
