### ISSUE TITLE
Events: Cannot Update Picture

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#37]
When trying to change the picture for an event, it doesn't actually save the new file on clicking save. To reproduce, try to change the App Image for Weekly Meeting. It lets you browse to find it, puts it in, and then on save, reverts back to the other file.

**Comment by fedorareis** [comment]
@kyle-fletcher The file is renamed on upload to a standard convention of events/event-name.jpg if you actually navigate to the url of the image you can see that upon clicking save and refreshing the image link the image actually changes.
