### ISSUE TITLE
Login from iOS & Android apps removes User profile settings

### ISSUE THREAD

**Issue by esolum** [CruCentralCoast/Keystone#4]
Logging in from either mobile app causes every boolean value in a User profile to be set to false. Any options that had been checked (such as "Is a community group leader", "Notifications Community Group Updates", and "Can administer the website") are now blank. I think it's an issue in `routes/api/authUtils.js` on line 24 when `user.getUpdateHandler(req).process(...)` is called.

**Comment by fedorareis** [comment]
I think this should be fixed from the most recent merge, could you check to see if that is true.

**Comment by tylerbwong** [comment]
I think this is fixed? @fedorareis

**Comment by fedorareis** [comment]
I'm closing this for now. If someone discovers that it is still an issue we can re-open it.
