### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#44]
The apps currently display social media links for Facebook, Instagram, Twitter, Snapchat, and YouTube. Since we have these social media channels for many of our ministries and we want them to show in the app based on the ministry that the user is subscribed to, the Ministry models will have to be updated to allow for Facebook, Instagram, Twitter, Snapchat, and YouTube information. I'm not sure if this is most helpful in a link format or in a format that would open up the page within those social media apps. And if it is a format that opens up the page within those apps, would it be a different format for iOS and Android?

**Comment by fedorareis** [comment]
The link fields have been implemented. @kyle-fletcher as far as the format part is concerned that is a question for the App teams.
