### ISSUE TITLE
New Sections in Models: Terms, Logos & Features

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#45]
As we continue thinking about the future, we need to be sure we are ready for other campuses to add in to what we are doing. Since other campuses don't use the same terminology for their ministries or have the same main logo, it would be helpful to have a Terms & Logos section that the apps can reference to change the terminology and logos throughout the apps. This main logo is not the one based on campus or ministry, but the one that displays on the startup splash screen and located at the top of the home page. I'm guessing that these features should be based on campus, not ministry. Helpful things to know include:

1) What do you call your small group Bible studies? Choices: Small Groups, Community Groups, Action Groups, Bible Studies
2) What do you call the teams that people can serve on? Choices: Ministry Teams, Core Team, Servant Team, Teams
3) Main Logo Image Upload
4) Home Page Background Image Upload

In addition, some ministries may not use all of the features of the app. It would be helpful to know which are needed for that ministry, so the apps can call up a different view screen for the portions of the app not used by that ministry. For instance, if they don't want to use Ridesharing, we can leave the Ridesharing portion there, but when a user navigates to that screen, it would pull up a screen saying that this feature has been disabled. I think this should be based on ministry, not campus since some smaller ministries on the same campus as a larger ministry may want different features.

**Comment by fedorareis** [comment]
We are no longer using Keystone so I am closing this issue.
